"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/header/Navbar";
import { LicenseInfo } from '@mui/x-license';
import { motion } from "framer-motion";
import FramerMotion from "./components/header/FramerMotion";

LicenseInfo.setLicenseKey('YOUR_LICENSE_KEY');


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className="flex flex-col" >
      <motion.div  
      initial={{ scale: 0 }}
    animate={{  scale: 1 }}
    transition={{
    type: "spring",
    stiffness: 260,
    damping: 20
  }}>
        <NavBar />
      </motion.div>
      {children}
    </body>
  </html>
  );
}
