name: Deployment
run-name: App is being deployed
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  DeployApp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: "Install Vercel CLI"
        run: npm i -g vercel@latest

      - name: "Pull environment information from Vercel"
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: "Build the app"
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: "Deploy to Vercel"
        run: vercel --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
